#!/usr/bin/env python3
"""Generate the small quarter-wave Q15 sine table used by the MCU."""

from __future__ import annotations

import argparse
import math
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
OUTPUT = ROOT / "modern/generated/zs407_sine_q15.h"


def render() -> str:
    values = [round(32767.0 * math.sin(math.pi * index / 128.0))
              for index in range(65)]
    lines = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "/* Generated by tools/generate-waveform-tables.py; do not edit. */",
        "#ifndef ZS407_GENERATED_SINE_Q15_H",
        "#define ZS407_GENERATED_SINE_Q15_H",
        "",
        "#include <stdint.h>",
        "",
        "static const int16_t zs407_sine_quarter_q15[65] = {",
    ]
    for offset in range(0, len(values), 8):
        chunk = ", ".join(str(value) for value in values[offset:offset + 8])
        lines.append("  " + chunk + ("," if offset + 8 < len(values) else ""))
    lines.extend(["};", "", "#endif /* ZS407_GENERATED_SINE_Q15_H */", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print("stale generated waveform table", file=sys.stderr)
            return 1
    else:
        OUTPUT.parent.mkdir(parents=True, exist_ok=True)
        OUTPUT.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
