#!/usr/bin/env python3
"""Generate deterministic C, Swift and TypeScript ZS407 contracts."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
SOURCE = ROOT / "modern/contracts/zs407_contract.json"
OUTPUTS = {
    "c": ROOT / "modern/generated/zs407_contract.h",
    "swift": ROOT / "modern/generated/ZS407Contract.swift",
    "typescript": ROOT / "modern/generated/zs407-contract.ts",
}


def macro(name: str) -> str:
    return name.upper().replace("-", "_")


def render_c(data: dict) -> str:
    protocol = data["protocol"]
    trace = data["trace"]
    lines = [
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        "/* Generated by tools/generate-contracts.py; do not edit. */",
        "#ifndef ZS407_GENERATED_CONTRACT_H",
        "#define ZS407_GENERATED_CONTRACT_H",
        "",
        f"#define ZS407_SCHEMA_VERSION {data['schema_version']}U",
        f"#define ZS407_PROTOCOL_MAGIC {protocol['magic']}U",
        f"#define ZS407_PROTOCOL_VERSION {protocol['version']}U",
        f"#define ZS407_PROTOCOL_MAX_PAYLOAD {protocol['maximum_payload_bytes']}U",
        f"#define ZS407_PROTOCOL_MAX_TRACE_POINTS {protocol['maximum_trace_points']}U",
        f"#define ZS407_TRACE_DB_SCALE {trace['power_scale_db']}U",
        f"#define ZS407_TRACE_INVALID_SAMPLE ({trace['invalid_sample']})",
        "",
    ]
    for group, prefix in (("commands", "COMMAND"), ("status", "STATUS"),
                          ("capabilities", "CAPABILITY")):
        for name, value in data[group].items():
            lines.append(f"#define ZS407_{prefix}_{macro(name)} {value}U")
        lines.append("")
    lines.extend(["#endif /* ZS407_GENERATED_CONTRACT_H */", ""])
    return "\n".join(lines)


def render_swift(data: dict) -> str:
    p = data["protocol"]
    t = data["trace"]
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by tools/generate-contracts.py; do not edit.",
        "public enum ZS407Contract {",
        f"    public static let schemaVersion: UInt8 = {data['schema_version']}",
        f"    public static let protocolMagic: UInt16 = {p['magic']}",
        f"    public static let protocolVersion: UInt8 = {p['version']}",
        f"    public static let maximumPayloadBytes = {p['maximum_payload_bytes']}",
        f"    public static let maximumTracePoints = {p['maximum_trace_points']}",
        f"    public static let traceDBScale = {t['power_scale_db']}",
        f"    public static let invalidTraceSample: Int16 = {t['invalid_sample']}",
        "",
    ]
    for group, enum_name, raw_type in (
        ("commands", "Command", "UInt16"),
        ("status", "Status", "UInt8"),
        ("capabilities", "Capability", "UInt32"),
    ):
        lines.append(f"    public enum {enum_name}: {raw_type} {{")
        for name, value in data[group].items():
            swift_name = name.split("_")[0] + "".join(
                part.title() for part in name.split("_")[1:]
            )
            lines.append(f"        case {swift_name} = {value}")
        lines.extend(["    }", ""])
    lines.extend(["}", ""])
    return "\n".join(lines)


def render_typescript(data: dict) -> str:
    p = data["protocol"]
    t = data["trace"]
    lines = [
        "// SPDX-License-Identifier: GPL-3.0-or-later",
        "// Generated by tools/generate-contracts.py; do not edit.",
        "export const ZS407Contract = {",
        f"  schemaVersion: {data['schema_version']},",
        f"  protocolMagic: {p['magic']},",
        f"  protocolVersion: {p['version']},",
        f"  maximumPayloadBytes: {p['maximum_payload_bytes']},",
        f"  maximumTracePoints: {p['maximum_trace_points']},",
        f"  traceDBScale: {t['power_scale_db']},",
        f"  invalidTraceSample: {t['invalid_sample']},",
        "  commands: {",
    ]
    for name, value in data["commands"].items():
        lines.append(f"    {name}: {value},")
    lines.extend(["  },", "  status: {"])
    for name, value in data["status"].items():
        lines.append(f"    {name}: {value},")
    lines.extend(["  },", "  capabilities: {"])
    for name, value in data["capabilities"].items():
        lines.append(f"    {name}: {value},")
    lines.extend(["  },", "} as const;", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true",
                        help="fail if generated files differ")
    args = parser.parse_args()
    data = json.loads(SOURCE.read_text(encoding="utf-8"))
    rendered = {
        "c": render_c(data),
        "swift": render_swift(data),
        "typescript": render_typescript(data),
    }
    stale = []
    for key, path in OUTPUTS.items():
        content = rendered[key]
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
    if stale:
        print("stale generated contracts: " + ", ".join(stale), file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
